### ISSUE TITLE
Pressing escape removes call

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#101]
Pressing escape should just stop sending, not remove the call using CWByCAT

**Comment by n4af** [comment]
Closed 4.45.5

**Comment by ny4i** [comment]
Did I introduce that regression?

Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

On Feb 12, 2016, at 3:23 PM, Howie Hoyt <notifications@github.com> wrote:

Closed #101 <https://github.com/n4af/TR4W/issues/101>.

—
Reply to this email directly or view it on GitHub
<https://github.com/n4af/TR4W/issues/101#event-549020540>.

**Comment by n4af** [comment]
No. N5AW complained that cwbycat was not working on esc.
I had it so escape stopped the cw but also cleared the call.
So changed it so esc only stops the cw. He then noted that hitting escape
twice, like wkey,
d/n clear the call.

Right now I told him to use alt-w. But i would like you to review the code
to ensure I d/n stomp on what you had added.

73, Howie

http://n4af.net

**Comment by ny4i** [comment]
This is not working right. Here is the scenario with 4.46.4:

1. In S&P mode, type a call and hit enter.
2. Program sends MYCALL and waits in the exchange box for input.
3. Hot ESC. no noticeable action. 
4. Hit ESC again and program clears the call window and goes to CQMODE.

This was working so I think the ESCAPE_proc is being too aggressive.

**Comment by ny4i** [comment]
After the 4.46.7 merge, this is still a bug. 
Howie - You are familiar with the ESC code, can you take a look at this please? This was in the ARRl DX CW test.

**Comment by n4af** [comment]
I will try to get to this as next bug fix.
99% chance it is that I am not resetting the switch set to do the clear.
Works for CQMode but not SAPmode.

http://n4af.net

**Comment by n4af** [comment]
fixed 4.46.7
