### ISSUE TITLE
Enable RITCLEAR under CWByCAT

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#108]
Allow RIT CLEAR to work like it does with WinKey (for supported radios).

**Comment by ny4i** [comment]
I need some more detail. What does CWBYCAT have to do with RITCLEAR? 

Tom
Principal Solutions Architect, ITIL®v3 
Better Software Solutions, Inc.
727-437-BSS1 (727-437-2771)
@BSSI_Consulting

**Comment by n4af** [comment]
User error, not set in the function keys

**Comment by n4af** [comment]
Sorry Tom I did not have it set in the function keys.



73, Howie

http://n4af.net

**Comment by ny4i** [comment]
Clearly the program should have known what you meant to do and acted accordingly. :)

Glad it was a false alarm!

Tom
Principal Solutions Architect, ITIL®v3 
Better Software Solutions, Inc.
727-437-BSS1 (727-437-2771)
@BSSI_Consulting

**Comment by n4af** [comment]
exactly so. stupid program :-)

73, Howie

http://n4af.net
