### ISSUE TITLE
TR4W loses sync with Wkey 

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#110]
A report that Wkey loses connection to TR4W

**Comment by n4af** [comment]
Not really sure of the root cause but force WK_RESET before initiating SENDCW
4.46.3

**Comment by n4af** [comment]
4.46.3 breaks sent exchange.

**Comment by n4af** [comment]
changed 4.46.3 to clearbuffer before initiating 
SendCrypticCWstring(Message); line 226 LogSubs1
This only flushes the cw buffer before an F key is processed.

**Comment by ny4i** [comment]
I see you commented it out, but just a note that the RadioObject.SendCW is ony called by CWBYCAT. The idea is this comes under the guise of a radio command so by definition it would be CWBYCAT only.

**Comment by n4af** [comment]
No.
Line 281 of LogCW calls him with Wkey:

if KeyersSwapped then                         // ny4i 4.
         begin
         InactiveRadioPtr.SendCW(Msg);
         end
      else
         begin
         ActiveRadioPtr.SendCW(Msg);  <<<<<<<<<<<<<<<<<<<<<<<<<
         end;

http://n4af.net

**Comment by ny4i** [comment]
OK. Now I need to figure this one out. I thought I added SendCW when I added CWBYCAT. Let me look again.

**Comment by ny4i** [comment]
Howie, I finished this and was testing with the WinKeyer. There were too many places where the FlushBuffer was called. The WinKeyer was not working. I could not tell if these were there before. I commented out three FlushBuffer calls that looked new. You can see my changes in the latest commit.

**Comment by n4af** [comment]
Ok. Yes, that could lead to problems for sure.

http://n4af.net

**Comment by n4af** [comment]
This will be 4.46.4

**Comment by n4af** [comment]
i have asked N5AW for an update on whether this can be closed.

**Comment by n4af** [comment]
closing- not able to reproduce this.
