### ISSUE TITLE
Some stability enhancements

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#116]
I set the Warnings compile option to find some missing things the compiler is complaining about. Things like procedures not returning results or variables not being set due to all assignments in a case (and possible some not done). This is an on going issue.

**Comment by n4af** [comment]
only 170 warnings to review ;-)

**Comment by ny4i** [comment]
I learn something new about Git all the time. I did not mean to merge this into Master but the way I created the branch in the repo did it for me.

Create the branch locally and in remote prior to any commits. :)
