### ISSUE TITLE
When CWByCAT is enabled, it should take priority

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#122]
Currently, the program now supports three modes of CW: CWBYCAT, WinKeyer, and serial port.

We should set a precedence for these three so they do not conflict. 

If any commands are processed because both CWBYCAT is active AND the radio model supports CWBYCAT, then do not do the WK commands or serial CW commands.

Thoughts?

**Comment by n4af** [comment]
That seemed to do the trick Tom

I now am sending CWBC on the TS590 !

73, Howie

http://n4af.net

**Comment by ny4i** [comment]
CWByCAT is processed first.
