### ISSUE TITLE
4.46.4 no radios connected, second ALTB causes abend

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#127]
Reported by YO2IS and recreated.

This seems to be fixed somewhere along the way to present 4.46.12 so it will probably close on introduction of 4.47

**Comment by ny4i** [comment]
There was an issue I fixed for if the bandmap was not up. A procedure result was not initialized properly and the procedure called exited out without setting anything. This caused an issue.

That was issue 115.

Tom
Principal Solutions Architect, ITIL®v3 
Better Software Solutions, Inc.
727-437-BSS1 (727-437-2771)
@BSSI_Consulting

**Comment by n4af** [comment]
Thanks Tom
