### ISSUE TITLE
When two copies of TR4W are run, second receives terse error message

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#139]
When two copies of TR4W are run, the second copy receives the following error message: "Cannot create file when the file exists". This is a unhelpful error message. I recommend the program detect another copy of itself and display a better error message explaining that "A copy of TR4W is already running".

**Comment by ny4i** [comment]
This item from [StackOverflow](http://stackoverflow.com/questions/459554/how-can-i-tell-if-another-instance-of-my-program-is-already-running) has some hints on doing this in Delphi.

**Comment by n4af** [comment]
Fixed in 4.48.4 module TR4W.DPR

**Comment by n4af** [comment]
https://github.com/n4af/TR4W/blob/master/tr4w/tr4w.dpr line 434
