### ISSUE TITLE
Bandmap does not clear all spots cleanly

### ISSUE THREAD

**Issue by gm0gav** [n4af/TR4W#141]
Clearing all spots leaves spurious characters for a short period

**Comment by gm0gav** [comment]
Fixed in  4.47.4, Killfocus procedure added to cleanly move focus away from bandmap

**Comment by gm0gav** [comment]
Fixed in 4.47.4, Killfocus procedure added to cleanly move focus away from bandmap

**Comment by ny4i** [comment]
Gav - There is some artifact left when dealeting a single spot though now.

**Comment by ny4i** [comment]
This is what I saw after I deleted a single spot.

![screenshot 2016-03-14 02 07 13](https://cloud.githubusercontent.com/assets/12401482/13736290/8996f3a0-e989-11e5-8db5-f41b8799c1aa.png)

I'm guessing but it seems that the code to delete a spot and atomically update the number of items in the spots array and then refresh only the items int he spots array is not exactly synchronized. This is an very event driven process so I would think there has to be some concurrency controls added (mutex, TCriticalSection, etc).

**Comment by gm0gav** [comment]
Noted the same, will resolve this week

**Comment by ny4i** [comment]
I'm taking a shot at this...

**Comment by ny4i** [comment]
I'm punting this for now. If I work in this too long, I will rewrite the whole thing as a real Delphi form with a real TList object filling the window. :)
