### ISSUE TITLE
 If TwoRadio is not set, Alt-D can still run.

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#146]
The code that handles Alt-D tests for SingleRadioMode, but twoRadioMode was false so SIngleRadioMode was not set.

Find out how this toggle is set. I believe these two booleans should be mutually exclusive but there must be some reason to have the two.

**Comment by ny4i** [comment]
Howie, Did I see you added a message so that if not in Two Radio mode, Alt-D would QuickDisplay an error? If so, this can be closed.

**Comment by n4af** [comment]
Hi Tom -

No, I have not added a message,but I can if you think it is confusing ?



73, Howie

http://n4af.net

**Comment by n4af** [comment]
fixed 4.48.3 to LogSubs2
