### ISSUE TITLE
Entering a DUPE in SAP Mode causes cursor to go to exchange field

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#172]
Entering a dupe call in S&P mode causes the call to delete and the cursor to move to the exchange field.

**Comment by ur7qm** [comment]
Supplement, if to check the DUPE press the Spacebar, then everything is working OK.

**Comment by n4af** [comment]
fixed 4.49.5

**Comment by n4af** [comment]
NOTE:
pls reference CTRL-J parm **AUTO DUPE ENABLE S and P**  for additional control
