### ISSUE TITLE
Connecting to dxc.ww1r.com:7300 causes crash

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#2]
When I select dxc.ww1r.com:7300 from the drop down in the DX Cluster window, the program crashes right after the connect. I suspect the program is receiving something from the cluster it does not expect. I will check this out with the debugger and see what we are receiving.

**Comment by n4af** [comment]
Hi Tom
Yeah , I have never been able to isolate, but there is a problem there

73, Howie ny4a

**Comment by n4af** [comment]
can't seem to get it to fail Tom. I have had it running all night.

73, Howie

**Comment by ny4i** [comment]
I confirmed this is a bug. It is on the connect. My guess is the banner text is too long on a single line and that is causing an issue. I will investigate more.

**Comment by ny4i** [comment]
I tested again and it does not fail. Closing for now...
