### ISSUE TITLE
Control-P fails to control rotor

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#216]
Redo Possible Calls (encompassing rotor control) was replaced with Control PTT by 4.53.9

**Comment by n4af** [comment]
4.54.5 will provide Redo Possible Calls function via CTRL-ALT-R
(note 'R', not 'P')
available in release 4.55

**Comment by ny4i** [comment]
That was sort of a dual use command. If you had a call in the call window, CTRL-P turned the rotor.

Tom
Principal Solutions Architect, ITIL®v3 
Better Software Solutions, Inc.
727-437-BSS1 (727-437-2771)
@BSSI_Consulting

**Comment by n4af** [comment]
just so. 
I moved it to ctrl-alt-r but (unfortunately) connected it to  the ptt menu.
4.55.5 should connect ctrl-alt-r back to redo-possible.
73, Howie
