### ISSUE TITLE
Add support for Winter Field Day

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#222]
http://www.winterfieldday.com/rules/

This is almost identical to Field Day but they categories are different (O, H, I).

**Comment by ny4i** [comment]
Howie - Did you see my email last week? I was curious if you were going to roll all your recent patches into Master if you have not already. I wanted to merge this and create a Pull request. Thanks

**Comment by n4af** [comment]
Hi Tom -

No, I did not -sorry.

I just pushed 4.56.8 to master, so it should be up to date.

73, Howie
