### ISSUE TITLE
Change verbage 'Floppy File Save'

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#240]
Reference changed to 'File Save

If you have 'Floppy file save' set in your TR4W/SETTINGS/TR4W.INI you will need to change it to 'File save' to avoid nag screen on startup.

**Comment by n4af** [comment]
4.56.11

**Comment by ny4i** [comment]
Howie - Do you think this should be File Save or “Backup Log or something like that?

I was just thinking it might be confused with the File Save on the File menu.

Tom
Principal Solutions Architect, ITIL®v3 
Better Software Solutions, Inc.
727-437-BSS1 (727-437-2771)
@BSSI_Consulting

**Comment by n4af** [comment]
Ok. I will change it to backup log in 4.56.12
