### ISSUE TITLE
QSO point method over ride not accepted

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#242]
config file QSO POINT METHOD =
over ride of qso points are not accepted.

**Comment by n4af** [comment]
QSOPointMethodType entry displacement for 
ThreePhoneFiveCWFourRTTY positioned wrong in array within module VC.pas
fixed 4.57.1

**Comment by ny4i** [comment]
Did I break that? I don't think I added point calculators.

Tom
Principal Solutions Architect, ITIL®v3 
Better Software Solutions, Inc.
727-437-BSS1 (727-437-2771)
@BSSI_Consulting

**Comment by n4af** [comment]
Hi Tom -

No. My adding/removing RadioYOK caused it.
Unfortunately, debugging it is difficult.

73, Howie
