### ISSUE TITLE
New propositions for YU-DX CONTEST

### ISSUE THREAD

**Issue by yu1lg** [n4af/TR4W#244]
Dear all,
 
Please find attached to this letter the new propositions for YU-DX CONTEST.
 
The term to hold the contest is still the third full weekend of April, i.e. Saturday at 12:00 UT up to Sunday at 11:59 UT (15/16th of April 2017).
 
[INTERNATIONAL_YUDX_HF_CONTEST.pdf (English)](https://github.com/n4af/TR4W/files/830465/INTERNATIONAL_YUDX_HF_CONTEST.pdf)

[YUDXC 2017.pdf (Serbian)](https://github.com/n4af/TR4W/files/830466/YUDXC.2017.pdf)

**Comment by n4af** [comment]
ADDED 4.57.5

**Comment by yu1lg** [comment]
Thank you very much

**Comment by n4af** [comment]
change mults so YU not awarded domestic mults:
"
Multiplier for non-YU stations:

The sum of worked DXCC countries + worked YU/YT COUNTIES on each band, regardless of the mode

Multiplier for YU stations:
The sum of worked DXCC countries on each band, regardless of the mode
"
added 4.57.7

**Comment by n4af** [comment]
changed code to allow YU to count as a Country.

**Comment by n4af** [comment]
revise YU to YU QsoPoints to 1

**Comment by n4af** [comment]
add yugoslav county full names to abbreviations yu.dom

**Comment by n4af** [comment]
note: -for YU stations- county entered is WYSIWYG

**Comment by n4af** [comment]
oops, this is already in YUDX.
