### ISSUE TITLE
CTRL-ALT-R accelerator not working to turn rotator

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#259]
The menu option works but nothing happens wen pressing the CTRL-ALT-R combo.

**Comment by n4af** [comment]
ctrl-alt-r is a windows shortcut and not available to TR4W.

4.125.4 assigns ctrl-p to Redo possible calls- if no call is entered. then rotor control is invoked.

**Comment by n4af** [comment]
This removes ctrl-P PTT activation and assigns to dual function redo possible calls/rotor control.

**Comment by ny4i** [comment]
If no call is entered, where does ALT-P turn the rotor to? I thought the idea was to turn it to the estimated location of the call in the call window? Principal Solutions ArchitectBetter Software Solutions, Inc. 727-437-2771On Aug 26, 2023, at 3:04 PM, Howie Hoyt ***@***.***> wrote:﻿
ctrl-alt-r is a windows shortcut and not available to TR4W.
4.125.4 assigns ctrl-p to Redo possible calls- if no call is entered. then rotor control is invoked.

**Comment by n4af** [comment]
Hi Tom -

Well, if no call is entered, trace shows him dropping thru
VisibleLog.DoPossibleCalls(CallWindowString);
on the way to
 RotorControl(LastHeadingShown);
which was previously set by
***@***.***);
resulting in no motion as rotor control is already set to the prev beam
heading ??

Are you thinking this should be titled something like 'beam heading'
instead of 'redo possible calls' ?

Thanks, Howie

**Comment by n4af** [comment]
of course, if ctl-j rotor parms are not set, we do not get past
***@***.***);
        DisplayGridSquareStatus(CallWindowString);
        VisibleLog.DoPossibleCalls(CallWindowString);

**Comment by ny4i** [comment]
No. Just asking. I admit I don’t know what REDO POSSIBLE CALLS does. I’ve never looked. Principal Solutions ArchitectBetter Software Solutions, Inc. 727-437-2771On Aug 26, 2023, at 5:33 PM, Howie Hoyt ***@***.***> wrote:﻿
of course, if ctl-j rotor parms are not set, we do not get past

***@***.***);

        DisplayGridSquareStatus(CallWindowString);

        VisibleLog.DoPossibleCalls(CallWindowString);

**Comment by n4af** [comment]
i think i will rename it, redo seems to just reload possible calls.

Tks, Howie
