### ISSUE TITLE
For SO2R, Dupesheet should display for only inactive radio

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#27]
**\* Migrated from Google Docs ***

Added new WINDOWS/DUPESHEET menu option enabling only dupesheet for inactive radio-needs rework

Units Affected:
 LOGSUBS1,MAINUNIT,SHAREDGLOBALS,TR4W.DPR,UMENU,VC

Reported by N4AF

**Comment by n4af** [comment]
Bandmap display SO2R resolves. but it tracks inactive and active radio, so user can  see/switch both.
