### ISSUE TITLE
Force IOTA island occupant to enter setup island designator with a dash

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#273]
For proper processing the occupant of an island **MUST** set up TR4W with a dash delimiting the continent from the island number.
The prompt has been changed to emphasize this. 
Hence 'NA-001' instead of 'NA001'

**Comment by n4af** [comment]
note: this does NOT change how the exchange is sent or recorded. 
eg, '599 NA001' would be sent and entered.
The generated cabrillo will contain 'NA-001'

**Comment by n4af** [comment]
fixed 4.61.4

**Comment by ny4i** [comment]
If th eexchange is entered incorrectly, we should have a message indicating to leave off the - in NA-034
