### ISSUE TITLE
Cannot find default log backup file

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#289]
Upon first installing the program, the BACKUP LOG FILE NAME is set to logback.tr4w. If I want to change the drive that file is on, I double-click the value and am presented with an Open file dialog. I navigate to the directory I want to save the file (in my case DropBox). The issue is that upon first setting this up, the file logback.tr4w is not in the directory so I cannot open it.

This dialog needs to allow selecting a directory without a file and then the first backup would create the log backup.

I recommend testing this by selecting a directory without a logback.tr4w file to duplicate this behavior. I am curious if anyone else confirms this when the file is not there already.

**Comment by n4af** [comment]
I am not sure what the win api call for opening a new file for write is.

not a perfect solution, but
what you can do is locate the line- or create it, in TR4W.INI in settings.
BACKUP LOG FILE NAME=E:\logbak.tr4w

This can be a new/non-existing file.

73, Howie

**Comment by ny4i** [comment]
I think the issue is the flags that are set in the dialog.

At line 432 in JCTRL2.PAS, this seems to be the code to show the file dialog.

if OpenFileDlg(TC_SELECTNEWFLOPPYFILESAVENAME, settingswindowhandle, nil, TempString, OpenMMTTYFlags)
        then FloppyFileSaveName := TempString;


In uDialogs.pas, I see OpenMMTTYFlags defined to be the following:

OpenMMTTYFlags                        = OFN_ENABLESIZING or OFN_NOREADONLYRETURN or OFN_EXPLORER or OFN_FILEMUSTEXIST or OFN_PATHMUSTEXIS

Since the OFN_FILEMUSTEXIST flag is set, this does not allow the dialog to return a new filename.

I suspect if we set the dialog flags to allow a new file (my guess by using similar flags but without OFN_FILEMUSTEXIST), then you would get the name back as the user typed it.

Tom
Principal Solutions Architect, ITIL®v3 
Better Software Solutions, Inc.
727-437-BSS1 (727-437-2771)
@BSSI_Consulting

**Comment by n4af** [comment]
Yes,
function OpenFileDlg in uDialogs is the culprit.

I can comment out line 892 to read
 ofn.Flags := Flags { or OFN_FILEMUSTEXIST} ;

but cannot be 100% sure it will not impact. ADIF import.

I think adif import is the only other client, so perhaps REMOVE
OFN_FILEMUSTEXIST from the dialog and adding to adif import:

In MainUnit.PAS routine  *menu_import_adif*:
if OpenFileDlg(nil, tr4whandle, 'ADIF (*.adi)'#0'*.adi',
TR4W_ADIF_FILENAME, OFN_HIDEREADONLY or OFN_ENABLESIZING)
to
if OpenFileDlg(nil, tr4whandle, 'ADIF (*.adi)'#0'*.adi',
TR4W_ADIF_FILENAME, OFN_HIDEREADONLY or OFN_ENABLESIZING *or
OFN_FILEMUSTEXIST*)

**Comment by n4af** [comment]
in reflecting on this, i think my last stmt makes the most sense.
Namely let the callers set the flags. Why should the open dialog be setting a flag for
file must exist ?

1) remove file must exist from OpenFileDialog
2) use explicit flags in callers to #1

**Comment by n4af** [comment]
This is going out for testing as 4.65.8

**Comment by ny4i** [comment]
That makes sense.

Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

On Nov 27, 2017, at 4:52 PM, Howie Hoyt <notifications@github.com> wrote:

in reflecting on this, i think my last stmt makes the most sense.
Namely let the callers set the flags. Why should the open dialog be setting
a flag for
file must exist ?

   1. remove file must exist from OpenFileDialog
   2. use explicit flags in callers to #1
   <https://github.com/n4af/TR4W/issues/1>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/n4af/TR4W/issues/289#issuecomment-347340639>, or mute
the thread

**Comment by n4af** [comment]
closing- this is picked up on 4.66.0

**Comment by ny4i** [comment]
It works well. Thanks

Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

On Dec 3, 2017, at 3:59 PM, Howie Hoyt <notifications@github.com> wrote:

closing- this is picked up on 4.66.0

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/n4af/TR4W/issues/289#issuecomment-348814027>, or mute
the thread
