### ISSUE TITLE
Fix scoring for Winter Field Day and initial setup question

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#301]
Currently, the initial setup asks for the ARRL FD class. This should be changed to Winter Field Day Class (I,O,H). Also, the score needs to be fixed as we the mults are a function of the band mode combination. 

From the rules:

> Mode and Band Multipliers: Count 1 multiplier for each mode operated per band. For example, operating CW and Phone on 80, 40, 15 and 10 meters, CW and PSK31 on 20m, FM on 2meters and 440 would be a total multiplier of 12x.

Also, check the Cabrillo output.

**Comment by n4af** [comment]
fixed 4.67.6
