### ISSUE TITLE
When working a dupe, there is no display of the prior QSOs

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#317]
It would be handy to have a way to show the prior QSO when a station is a dupe. I did not see a way to do this.

**Comment by n4af** [comment]
ctrl-j AUTO DUPE ENABLE x where x can be
CQ  (or)
S&P

**Comment by ny4i** [comment]
Does that show the prior dupes then?

**Comment by n4af** [comment]
Yeah. Give it a try. Sri I on sucky tablet.
H

**Comment by ny4i** [comment]
Actually, I found it out. As you said, if I entered a call and it is a dupe, then just hit ALT-L to show prior entries. That takes care of it for me.
