### ISSUE TITLE
Column Dupesheet Enable broken

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#32]
Migrated from Google Docs

Dupesheet works, but will not switch to call district by column mode

**Comment by n4af** [comment]
CTRL-J Column Dupesheet Enable effectively switches between the two modes.

73, Howie

**Comment by ny4i** [comment]
So is this closed as fixed, works as intended, etc?
Principal Solutions Architect, ITIL®v3 
Better Software Solutions, Inc.
727-437-BSS1 (727-437-2771)
@BSSI_Consulting

**Comment by n4af** [comment]
Hi Tom -

This should be closed as fixed.
I use it once a week in the thursday NCCC sprint.

Tks, Howie

http://n4af.net
