### ISSUE TITLE
Question on compatibility with winkey2 interfaces.

### ISSUE THREAD

**Issue by ur7hfo** [n4af/TR4W#337]
Question on compatibility with winkey2 interfaces.
I have a key from k3ng, it works with the program n1mm, and does not want to work with the program tr4w. Maybe you need additional settings from my side? Tell me if you can.

**Comment by n4af** [comment]
I have no way to answer this.
TR4W supports the K1EL winkey-- I own 3 of them and all work as designed.

73, Howie N4AF

**Comment by ok1rr** [comment]
Here works without any problem in both Windows and Linux. Works both 
Winkey and Tinykeyer (based on the K3NG Arduino keyer)...

73,
Martin, OK1RR

Dne 15.3.2018 v 10:18 ur7hfo napsal(a):
> Question on compatibility with winkey2 interfaces.
> I have a key from k3ng, it works with the program n1mm, and does not want to work with the program tr4w. Maybe you need additional settings from my side? Tell me if you can.
>

**Comment by ur7hfo** [comment]
Sorry, I already figured it out myself. For work, it was necessary to disable the automatic reset at arduino. Disabling automatic reset, everything worked fine!
