### ISSUE TITLE
Add option to automatically download latest CTY.DAT

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#340]
Add an option to retrieve the CTY.DAT file from this link: http://www.country-files.com/cty/cty.dat and place in the proper directory.

Extra credit to go check the file to see if there is a newer version. 

I recommend rather than using the Win32 API approach that the program currently does to make use of the Indy Library to retrieve a web page. This is with the TIdHTTP object.
```delphi
function TForm.HttpGet(const url: string): string;
var
  responseStream : TMemoryStream;
  html: string;
  HTTP: TIdHTTP;
begin
  try
      try
        responseStream := TMemoryStream.Create;
        HTTP := TIdHTTP.Create(nil);
        HTTP.Get('http://www.country-files.com/cty/cty.dat', responseStream);
        SetString(html, PAnsiChar(responseStream.Memory), responseStream.Size);
// Once downloaded, save at CTY.DAT in the right place
        result := html;
      except
        on E: Exception do
            Global.LogError(E, 'ProcessHttpRequest');
      end;
    finally
      try
        HTTP.Disconnect;
      except
      end;
    end;
end;
```

**Comment by n4af** [comment]
Sounds good Tom, but I do not how to do it with indy.

What I have done of late is just roll latest cty.dat into the monthly
update.

73, Howie

**Comment by ny4i** [comment]
I can do it. I put an example of using TIdHTTP in the ticket in case anyone wanted to take a crack at it.

I put things in the issues so I do not forget them. 
Tom
Principal Solutions Architect, ITIL®v3 
Better Software Solutions, Inc.
727-437-BSS1 (727-437-2771)
@BSSI_Consulting

**Comment by ny4i** [comment]
Do you mean we already have code in there to download the CTY.DAT file? If so, I missed that.

Tom
Principal Solutions Architect, ITIL®v3 
Better Software Solutions, Inc.
727-437-BSS1 (727-437-2771)
@BSSI_Consulting

**Comment by n4af** [comment]
NO. Extant code commented out to check and update trlog - i think vc.pas
i just meant it could act as a template...

**Comment by ny4i** [comment]
I understand. Better to do it with Indy so let me look at that.

Thanks,

Tom
Principal Solutions Architect, ITIL®v3 
Better Software Solutions, Inc.
727-437-BSS1 (727-437-2771)
@BSSI_Consulting

**Comment by n4af** [comment]
add to 4.75.3 in absence of indy code change...

**Comment by ny4i** [comment]
Thanks for implementing this. Sorry I have been out of pocket for a long time. I do intend to get back to this stuff soon.

**Comment by n4af** [comment]
FB Tom

73, Howie
