### ISSUE TITLE
+ in CW message sends 000 instead of PREV #

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#349]
The LIST of Commands states that + sends the Prev #. I read this to mean the previous QSO exchange NR. 

I needed this as I am operating remotely so I do not have a paddle to send the prior number. I must be missing something as after I entered the other stations NR, he asked for a fill on my number. I had already hit enter so if I hit the macro that has #, I get the next serial number.

**Comment by n4af** [comment]
something like ctrl-j AUTO QSO NUMBER DECREMENT, but in pileups right now...

**Comment by ny4i** [comment]
Thanks! That handles that but we should check if + is working as it is supposed to do. Good luck!

**Comment by n4af** [comment]
yes, if i can remember, will remove += from the list of commands.
Lets keep this open and I will code against this issue #

**Comment by n4af** [comment]
removed Prev # command list as this should not be done via command, rather by using CTRL-J AUTO QSO NUMBER DECREMENT = TRUE
changed in 4.71.5

**Comment by ny4i** [comment]
I’m curious if this was just a bug where the + calculation didn’t get set
properly. I see no harm to have both options for flexibility.

There might be a case where one wants the previous number when the callsign
field has something in it.


I have to check the code though.

Tom

Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

On May 28, 2018, at 7:50 AM, Howie Hoyt <notifications@github.com> wrote:

removed Prev # command list as this should not be done via command, rather
by using CTRL-J AUTO QSO NUMBER DECREMENT = TRUE
changed in 4.71.5

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/n4af/TR4W/issues/349#issuecomment-392506168>, or mute
the thread
