### ISSUE TITLE
QSO Party Additions

### ISSUE THREAD

**Issue by KQ7TJ** [n4af/TR4W#362]
I'd like to see more US State QSO Parties added:  The Weekend of October 12-14, 2018 had Pennsylvania, Arizona, and Nevada QSO Parties running simultaneously and none of them are in TR4W.  I tried, and failed miserably, to create a "New Contest" that would allow me to enter Contacts with the various formats - PA & NV required serial numbers and counties, AZ just RST and County.  I tried starting with the CA QSO Party format and it would not allow entry of the other state counties.  I tried the General QSO format and it wanted names: not part of the exchange.  I have pretty nearly ZERO programming skills, but thought I could at least modify a contest format to suit my needs: no luck!  So maybe I'm raising 2 issues here: 1) a request to add the QSO Parties, 2) a request to make it easier to modify contest formats to suit one's needs to log an unsupported contest:  such as having a check sheet somewhere where you could check off the appropriate boxes for the exchange.  Just having that and a dupe check allowing same station contacts on all bands and modes would at least allow one to somewhat efficiently log contacts.

**Comment by n4af** [comment]
Hello Tom -

Have you looked thru the U.G. on tr4w.net ? pp 80 ?
http://tr4w.net/TR4W_User_Manual_4.01b.pdf

Let me take you thru the *Arizona* QP to get you started.

1) You will need to translate the counties into a DOMestic (DOM) file.
a simple version WOULD BE:

APH = APH
CHS = CHS
CNO = CNO
GLA = GLA
GHM = GHM
GLE = GLE
LPZ = LPZ
MCP = MCP
MHV = MHV
NVO = NVO
PMA = PMA
PNL = PNL
SCZ = SCZ
YVP = YVP
YMA = YMA

we need to put the file into directory DOM under our main TR4W directory.
Ok, so the domestic file for the ARIZONA QP now exists.

NOTE: contest sponsors are not good about listing their counties in machine
readable/ascii format.
If you do not know how to make the dom, ASK - as someone may have already
created it.
For example PA_CTY.DOM is more complex but I will probably put out a PA QP
addition to TR4W.
In the meantime, http://tr4w.net/pa_cty.dom  should work.

Next we are going to create the CUSTOM CONFIG for the AZ QP (per the U.G.
writeup)

You want something like:
*;AZ QSO Party *
*MY CALL = N4AF*
*CONTEST TITLE = ARIZONA QSO PARTY*
*EXCHANGE RECEIVED = RST DOMESTIC QTH*
*DOMESTIC FILENAME = AZ.DOM*
*CONTEST NAME = ARIZONA QSO PARTY*
*DOMESTIC MULTIPLIER = DOMESTIC FILE*
*QSO POINT METHOD = ONE PHONE TWO CW *
*MULT BY BAND = FALSE*
*MULT BY MODE = TRUE*
*MULTIPLE BANDS = TRUE*
*MULTIPLE MODES = TRUE*

If you do not already have a *CUSTOM CONFIG  directory under TR4W*, create
it, and place the file in it using a name of your choice and filetype of cfg
so ARIZONA.CFG would contain the above lines.

Summary:

1) create a DOM file with the sections
2) create a CUSTOM CONFIG with the actual configuration for the contest
3) start up TR4W . it should list your existing contests AND the CUSTOM
CONFIG directory. Clicking on CUSTOM CONFIG should list your custom
configurations--
in this case, ARIZONA.CFG. Select the cfg and enjoy the contest.

Hope that helps/73, Howie N4AF

**Comment by KQ7TJ** [comment]
Thank you, Howie – that helps A LOT!  I did look at that section of the manual and failed to create a contest file that would work.  First thing I run into is it will not allow me to make any changes and I have to run Notebook as an Administrator – always trips me up.  From there I get lost pretty quickly as I am not conversant in programming lingo.  I got confused following the manual’s instructions as to when I should be opening TR4W vs when I should be going to the files in the computer.   This is fairly low priority for me, as for the most part TR4W contains the contests I need.  But just to torture myself and learn something new I will give it a try when I have time.  “Learn by destroying” is my motto.  So it could get ugly.  J  But TR4W seems bullet proof enough that I don’t think I will break it in the process, and the worst case scenario would be I have to uninstall and reinstall it if I really screw up!  I have all my contest logs safely saved outside of TR4W in the event I blow it up.  

 

73,

Tom Johnson

KQ7TJ

**Comment by KQ7TJ** [comment]
PS: Good call on the PA Party:  of the three that was the one that had the most participants and would be the most appropriate one to add to TR4W’s supported contests.

Tom

**Comment by n4af** [comment]
FB Tom.

BTW, I have placed the .dom for nevada into the latest copy of 4.74.3 in
the dom directory.

73, Howie

**Comment by n4af** [comment]
latest copy of 4.74.3 should also place illinois_cty.dom in the dom directory.

**Comment by n4af** [comment]
note: AZ QP allows for MULTIPLIERS by band, so changed
MULT BY BAND = FALSE    
to
MULT BY BAND = TRUE

**Comment by KQ7TJ** [comment]
Great, thank you! It was actually the Nevada QSO Party that was my stimulus
for getting on the air, as I live in Carson City, NV.  But my fellow
Nevadans apparently weren't very excited about the party: I only heard ONE
NV QSO CQ, whereas I heard a lot of PA stations, and about 1/2 as many AZ
stations. So considering PA is farthest from me, I'd say that indicates
there were many more participants in the PA Party than the others. Probably
due to the much greater PA population.

**Comment by KQ7TJ** [comment]
BTW I actually came in FIRST PLACE for Carson City / County, NV, in the
2018 7th Area QSO Party, but that's not much of a testament to my station
or contesting skills: it's more an indication of the low level of
participation in my area. I wouldn't be surprised if I was the ONLY Carson
City contestant, LOL. But I couldn't have done it without TR4W. :-)
