### ISSUE TITLE
CAT RTS problem

### ISSUE THREAD

**Issue by S52CQ** [n4af/TR4W#364]
Hi,

as per [this information](https://github.com/df8oe/UHSDR/issues/1603) would you please check RTS issue [described here](https://github.com/n4af/TR4W/issues/290). 

I did try Ctrl+J PTT via option, but RTS just does not release TX after CW is over.

73 de S52CQ, Jure

**Comment by S52CQ** [comment]
Hi,

there's been a new development, can you please check [this link ](https://github.com/df8oe/UHSDR/issues/1603)down at the bottom.

**Comment by n4af** [comment]
is this virtual or real?
If emulation I have already said we do not support.

If a real physical transceiver, pls specify
step by step instruction to recreate on a (TS480 ?)
