### ISSUE TITLE
The RIT display does not show as a decimal

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#377]
The RIT display on the radio windows did not show as a decimal value. On both the K3 and Icom radio, a RIT of 1.65 would show up as 165. This should be changed to more accurately reflect the radio display.

**Comment by n4af** [comment]
Can this be closed ??
Tks, Howie

**Comment by ny4i** [comment]
I’ll have to check it out.

**Comment by n4af** [comment]
ok. seems to work 4 me...
