### ISSUE TITLE
Add new ARRL section of PE

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#397]
Effective April 1, 2020, there is a new section abbreviated PE for Prince Edward Island. Would that just one a change to ARRLSECT.DOM?

http://www.arrl.org/news/radio-amateurs-of-canada-announces-a-new-section

**Comment by ny4i** [comment]
I checked the June release and while PE is in the list of sections, the program does not let you enter it. You have to enter PEI. That is because the DOM file has PE = PEI. Shouldn't that be PE = PE or PE = PE, PEI?

**Comment by n4af** [comment]
Good find Tom- btw, thanks the mult in WPX ;-)

Could you verify this fixes it <https://tr4w.net/4.89/tr4w_setup_4_89.1.exe>
?

73, Howie

**Comment by ny4i** [comment]
Yes, that fixes it. Thanks.

I figured it is hard for the NY4 calls to find another :) I did see NY4F on as well.

73,

Tom 
Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771
