### ISSUE TITLE
TR4W FAILS TO POPULATE  HQ MULTS on IARU ADIF IMPORT

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#40]

**Comment by ny4i** [comment]
This is no doubt related to the parser issues with the ADIF importer referenced inn issue #402

**Comment by ny4i** [comment]
I fixed this in my current branch fort ADIF processing. HQ is a custom field so I used look for APP_TR4W_HQ and APP_N1MM_HQ.

**Comment by n4af** [comment]
whoa, you been busy.
this should pickup both fixes. <https://tr4w.net/4.90/tr4w_setup_4_90.3.exe>

Thanks, Howie

**Comment by ny4i** [comment]
This does work properly in at least the code in my ImportADIFFixes Branch. So when it is ultimately merged, this can close. I will close it tentatively for now.

**Comment by n4af** [comment]
Hi Tom -

This went up as 4.90.4 <https://tr4w.net/4.90/tr4w_setup_4_90.4.exe>

Thanks, Howie
