### ISSUE TITLE
Rewrite the ADIF processing

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#402]
Create a new class to process ADIF records for import and export. Make sure to include all known ADIF 3 fields according to the latest specification. This will also fix bug #40

**Comment by n4af** [comment]
FB Tom -

Tks, Howie

**Comment by ny4i** [comment]
Just so I do not forget, as part of this, I fixed that when the contact was a non-RTTY digital contact, the Cabrillo file now sets the mode to DG instead of defaulting to RY.
