### ISSUE TITLE
Frequency polling with the Elecraft K2

### ISSUE THREAD

**Issue by SM6FPC** [n4af/TR4W#482]
Frequency polling the Elecraft K2 is eratic and is getting worse with versions above 4.96. With v4.86 Windows XP and the K2, the frequency is still logged correctly when the rig switches from RX to Tx, but not displayed continuosly. I also see a warning "Operating Split" now and then. With the 4.97.1 version I have to force a band switch by pushing the K2 bandswitch buttons to update the frequency. The Auto CQ may restart in the middle of the previuos message and now and then skips a CQ message (long pauses). I have found a workaround by using the LP-bridge software by N8LP. From the LPB2 manual: "LPB2 actually intercepts and buffers the additional polling traffic and responds immediately without sending the additional polling commands to the rig, which reduces serial traffic and eliminates packet collisions."  The LPB2 is transparent to other commands so "CW by CAT" is OK.
Letting LPB2 do the polling solves all the problems described above with any version of TR4W. Even the automatic swith from CQ to S&P mode when the frequency changes now works perfectly. There is one drawback. The LPB2 will not run under Windows 10. (for LPB2 see www.telepostinc.com) With Windows 10 and TR4W 4.96 without LPB2 I see the same problems but switching the rig from Rx to Tx still updates the frequency, so the log is acceptable. 
With my old IC725 I see no polling problems. Shortening the poll time to 10ms gives a few more correct readings with the K2. I can see the polling request in the LPB2 software window: 10 times "IF;" then one "FB;" command, looks OK to me. I noted a polling issue with the K3 from 11 Dec 2020. (Peter SM6FPC)

**Comment by n4af** [comment]
Hello Peter -

I am not able to reproduce that.
Hundreds of qsos a week on two k3's in so2r on CW using Windows 10 and 4.97

73, Howie N4AF

**Comment by SM6FPC** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
span.DefaultFontHxMailStyle
	{mso-style-name:"Default Font HxMail Style";
	font-family:"Arial",sans-serif;
	color:windowtext;
	font-weight:normal;
	font-style:normal;
	text-decoration:none none;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:70.85pt 70.85pt 70.85pt 70.85pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by SM6FPC** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
span.DefaultFontHxMailStyle
	{mso-style-name:"Default Font HxMail Style";
	font-family:"Arial",sans-serif;
	color:windowtext;
	font-weight:normal;
	font-style:normal;
	text-decoration:none none;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:70.85pt 70.85pt 70.85pt 70.85pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by n4af** [comment]
This is very difficult to read.
Yes, certainly any problem related to CAT speed would be problematical.

73, Howie

**Comment by SM6FPC** [comment]
I just checked the Elecraft forum for ”K2 and Prolific”. There are some warnings for old Prolific chipsets (like mine) in these threads. I Think I will buy a new non Prolific USB to serial. I will comment it on the GitHub issue when I see some results useful to other K2 owners.Thank’s for putting me on this trail. Always helpful to discus with others. Skickades från E-post för Windows 10 av Peter van Haeringen Från: Howie HoytSkickat: den 17 februari 2021 17:52Till: n4af/TR4WKopia: SM6FPC; AuthorÄmne: Re: [n4af/TR4W] Frequency polling with the Elecraft K2 (#482) This is very difficult to read.Yes, certainly any problem related to CAT speed would be problematical.73, Howie—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ny4i** [comment]
Prolific usb interfaces should be thrown in the trash. They are not reliable. 

Principal Solutions Architect
Better Software Solutions, Inc. 
727-437-2771

**Comment by SM6FPC** [comment]
Yes, the above got I little bit hard to read...
Howie wrote more diplomatically: "Yes, certainly any problem related to CAT speed would be problematical."
I just bought and installed a new USB to Serial. Now TR4W runs on both laptops in all versions without the LP-bridge software. Problem solved!! TU Howie and Tom for putting me on the right track!
