### ISSUE TITLE
Filter bandmap by entries in Initial exchange file

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#495]
Please add the ability to only write out bandmap entries that match content of the Initial Exchange file.

**Comment by n4af** [comment]
A new configuration command will be added-
IE SWITCH
When set to 'TRUE', only spots matching entries in the active initial exchange file will be written out to the bandmap.

**Comment by n4af** [comment]
4.98.8

**Comment by ny4i** [comment]
What is an example of something in the Initial Exchange file that I could limit? By call, location, mode, etc?

Tom
Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

**Comment by n4af** [comment]
No, only by call.
So if the call is in the IE, a spot for that call should make it into the bm.

**Comment by n4af** [comment]
i have used this many times in CWT.

**Comment by n4af** [comment]
note: ie_switch searches BOTH the initial.ex AND TRmaster.dta files
