### ISSUE TITLE
Update UDP records to match latest N1MM UDP specification

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#510]
N1MM has made some changes to the UDP records. Check that TR4W is sending the same fields on all record types. Add any new records too.

Specifications are available here: https://n1mmwp.hamdocs.com/appendices/external-udp-broadcasts/

**Comment by n4af** [comment]
uploaded as 4.100.10

**Comment by ny4i** [comment]
I may have broke something here in the program changing bands. It sees the frequency ok but is not changing th ebands. This release should not go anywhere yet.

**Comment by ok1rr** [comment]
Today tried MWC contest again. A "7" multiplier appeared. There are NO 
numerals as mults, a mult must be A to Z (max. 26, per band).

73,
Martin, OK1RR

**Comment by n4af** [comment]
I am confused are you commenting on the UDP update of 4.100.10 or an
entirely new problem re: release 4.100.??

73, Howie

**Comment by n4af** [comment]
rr.

**Comment by ny4i** [comment]
Yep I broke something. Can you blackout that branch?

That is safest thing.

Tom
Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

**Comment by n4af** [comment]
ok. i have reset the head back two commits and then
re-commited subsequent maintenance, so (hopefully) 4.100.10 code is gone.

**Comment by ny4i** [comment]
This was fixed along the way
