### ISSUE TITLE
Show TR4W execution path

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#512]
It can be confusing knowing the location of TR4W presently executing.

**Comment by n4af** [comment]
CTRL-P will now show TR4W_PATH_NAME
4.100.5

**Comment by ny4i** [comment]
Wasn’t CRTL-P some other command?

Just a recollection.

Tom
Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

**Comment by n4af** [comment]
yeah, ptt. i gonna move ptt to ctrl-b

73, Howie

**Comment by ny4i** [comment]
Just so I can share my thoughts, I am never thrilled when we change keystrokes. Users may get used to the prior one. Does it really need to have a shortcut? Can you not just have the menu option with no shortcut?

Tom
Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

**Comment by n4af** [comment]
Ok, i will change it back...

**Comment by n4af** [comment]
show execution path is changed to CTRL-B
