### ISSUE TITLE
Cabrillo export - Operators

### ISSUE THREAD

**Issue by yu7aop** [n4af/TR4W#535]
Hi, when I export a cabrillo file (or some other), OPERATORS - does not show what I entered, but only the primary call sign. 73, Boris YU7MW

**Comment by ny4i** [comment]
Operators is generated by checking the operator field of each contact.

If you did not enter the operators during the contest (with OPON), you will have to manually update the field.

Tom NY4I


Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

**Comment by yu7aop** [comment]
OK, Tom, tnx....
73
