### ISSUE TITLE
Change SHIFT KEY ENABLE

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#540]
Shift Key Enable previously bumped both the VFO and RIT.
This changes SHIFT KEY ENABLE to only bump the VFO frequency.

**Comment by n4af** [comment]
4.105.6

**Comment by ny4i** [comment]
I believe if RIT is on, it’s supposed to bump RIT. 

Principal Solutions Architect
Better Software Solutions, Inc. 
727-437-2771

**Comment by n4af** [comment]
KJ9C mentioned an arm injury and using shift to tune.
Actually that seems more useful- the way it is was set,
with SHIFT KEY ENABLE, the RIT AND VFO were bumped.

I commented out the RIT bump.

73, Howie

**Comment by ny4i** [comment]
If RIT is off I agree. My point is if RIT is on, it should tune RIT. That is how it is documented I believe. 

Tom

Principal Solutions Architect
Better Software Solutions, Inc. 
727-437-2771
