### ISSUE TITLE
NCCC Sprint fails to import QTH

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#550]
Export of QTH is ok but import fails to read the QTH in.

**Comment by n4af** [comment]
Fixed 4.105.13

**Comment by ny4i** [comment]
Thanks for doing these. I was sure there would be some issues when I rewrote the ADIF parser. But the code is better for it. 

Tom

Principal Solutions Architect
Better Software Solutions, Inc. 
727-437-2771
