### ISSUE TITLE
CQWW fails to import zone

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#553]
Import of extant log fails to import the SRX_String zone content

**Comment by n4af** [comment]
Assign 4.105.16

**Comment by n4af** [comment]
fix 4.105.16

**Comment by ny4i** [comment]
We need to enlist the user community and ask them to each pick a contest to test export and import to see if they run across any issues.

Tom

**Comment by n4af** [comment]
Ok, UR7QM will investigate - if he is not a long hauler.
On the contest id in cbr, all seems ok in my submitted 4.105.16 log AND a new test log.

Howie

**Comment by ny4i** [comment]
I mean contest ID in ADIF. 

Tom

Principal Solutions Architect
Better Software Solutions, Inc. 
727-437-2771

**Comment by n4af** [comment]
<sigh>.
yeah, i will take a look <ISSUE 554>

tks, howie

**Comment by ny4i** [comment]
I looked but can’t figure out where the _ are being removed unless there is a function called doing that somewhere.

Tom
