### ISSUE TITLE
ADIF export cqww wrong

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#554]
<CONTEST_ID:6>CQWWCW
should be
<CONTEST_ID:8>CQ-WW-CW
in the generated ADIF file

**Comment by ny4i** [comment]
In PostUnit, there is logic to say that if the ADIFNAme(might have the wrong name)  is NOT blank (that is in the contests array), use that. Otherwise, use the contest name. But as I mentioned, it was not clear what is removing the _ from the name.

Tom

**Comment by n4af** [comment]
fixed [4.105.17](https://tr4w.net/4.105/tr4w_setup_4_105.17.exe)

**Comment by ny4i** [comment]
What was the issue?

Tom

**Comment by n4af** [comment]
VC contests array iine for cq-ww-cw ADIF=''
had ADIF='CQWWCW'

**Comment by n4af** [comment]
https://github.com/n4af/TR4W/commit/e3ffd444ad52830a251c03aef5bbcdc63309c5b9

**Comment by ny4i** [comment]
I see it now. Did you fill in the ADIFNAME with CQWWCW? I did not see that originally in my branch but I see it is there now.

Tom

**Comment by n4af** [comment]
probably...
