### ISSUE TITLE
UBA fails to import domestic mult 'D'

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#559]
UBA CW and SSB fail to import in the domestic mults.

**Comment by n4af** [comment]
assign 4.106.7

**Comment by ok1rr** [comment]
In 4.106.7 DX Cluster connection does not work. 4.106.6 is OK.

73,
Martin, OK1RR

**Comment by n4af** [comment]
I cannot reproduce that here.
Can you reproduce under windows ?
The change is a one line change to ParseAdif that should not impact cluster
connection.
