### ISSUE TITLE
Add missing K4 Network commands

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#572]
It looks like I missed a few commands in the network implementation.

Specifically, RITBumpUp, RITBumpDown, VFOBumpUp, VFOBumpDown.

**Comment by ny4i** [comment]
What do you mean without CAT? You have CWByCAT control with Ethernet or serial. When you sent that, the KY command is used to send the CW.

I may not be understanding your question though.

Tom
Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

**Comment by ok1rr** [comment]
I meant without CAT via USB. I plan to use CWByCAT via Ethernet. No 
experience with this, I always used an external keyer for years. Now I 
would try the internal keyer and my idea was to evaluate the already 
present Ethernet connection. This stuff is very new to me.

73,
Martin, OK1RR

Dne 10. 02. 22 v 19:54 Tom Schaefer napsal(a):
> What do you mean without CAT? You have CWByCAT control with Ethernet or serial. When you sent that, the KY command is used to send the CW.
>
> I may not be understanding your question though.
>
> Tom
> Principal Solutions Architect
> Better Software Solutions, Inc.
> 727-437-2771
>

**Comment by ny4i** [comment]
Ok well if you set CWbyCAT, the radio will send CW no matter which interface you use. You can still use a USB connection on the K4 for CW via DTR (and FSK via RTS). 

Tom

Principal Solutions Architect
Better Software Solutions, Inc. 
727-437-2771

**Comment by ok1rr** [comment]
Tested CW via TCPIP & K4

Although the radio control works perfectly with my K4, CW sending not. 
The spaces are unnaturally long, the words are torn and a question mark 
is added at the end of the message. Tested in both Linux (Wine) and 
Windows 7. Results the same. The program is therefore unusable.

73,
Martin, OK1RR
K4 #0300


Dne 10. 02. 22 v 23:57 Tom Schaefer napsal(a):
> Ok well if you set CWbyCAT, the radio will send CW no matter which interface you use. You can still use a USB connection on the K4 for CW via DTR (and FSK via RTS).
>
> Tom
>
> Principal Solutions Architect
> Better Software Solutions, Inc.
> 727-437-2771
>

**Comment by ok1rr** [comment]
I meant spaces between characters. The spaces between dots and dashes 
are OK, the characters sounding great...


Tested CW via TCPIP & K4


Although the radio control works perfectly with my K4, CW sending not. 
The spaces are unnaturally long, the words are torn and a question mark 
is added at the end of the message. Tested in both Linux (Wine) and 
Windows 7. Results the same. The program is therefore unusable.

73,
Martin, OK1RR
K4 #0300


Dne 10. 02. 22 v 23:57 Tom Schaefer napsal(a):
> Ok well if you set CWbyCAT, the radio will send CW no matter which 
> interface you use. You can still use a USB connection on the K4 for CW 
> via DTR (and FSK via RTS).
>
> Tom
>
> Principal Solutions Architect
> Better Software Solutions, Inc.
> 727-437-2771
>

**Comment by ny4i** [comment]
Let me check on it. 

Tom

Principal Solutions Architect
Better Software Solutions, Inc. 
727-437-2771

**Comment by ny4i** [comment]
Martin,

I verified this just now and I do apologize. It was a bug I discovered but forgot to fix.

I will get it done by this weekend.

Pleases use the WinKeyer or the just the RTS sending on the USB serial port in the meantime (that works well on the K4).

Tom NY4I 
Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

**Comment by ny4i** [comment]
Adding Martin’s email.

Tom
Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

> Begin forwarded message:
> 
> From: ***@***.***" ***@***.***>
> Subject: Re: [n4af/TR4W] Add missing K4 Network commands (Issue #572)
> Date: March 9, 2022 at 9:39:06 AM EST
> To: n4af/TR4W ***@***.***>
> Cc: n4af/TR4W ***@***.***>, Assign ***@***.***>
> 
> Martin,
> 
> I verified this just now and I do apologize. It was a bug I discovered but forgot to fix.
> 
> I will get it done by this weekend.
> 
> Pleases use the WinKeyer or the just the RTS sending on the USB serial port in the meantime (that works well on the K4).
> 
> Tom NY4I 
> Principal Solutions Architect
> Better Software Solutions, Inc.
> 727-437-2771
>
