### ISSUE TITLE
On a K4, when a preprogrammed message contains > (RIT clear), program crashes

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#585]

**Comment by n4af** [comment]
i wonder:
a) whether he meant on k4
b) whether also applies to xit clear:
procedure TK4Radio.RITClear(whichVFO: TVFO);
begin
   Self.SendToRadio(whichVFO,'RC','');
end;

procedure TK4Radio.XITClear(whichVFO: TVFO);
begin
   Self.SendToRadio(whichVFO,'RC','');
end;

**Comment by ny4i** [comment]
Oops. That looks like a copy6 and paste error. I will fix that too.

I emailed to ask.

Tom
Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

**Comment by ny4i** [comment]
My mistake. According tot he book, RC; clears both RIT and XIT. No way to clear just one.

**Comment by n4af** [comment]
testing on K3, seems to work FB.

**Comment by ny4i** [comment]
I tested with the clear command but not with the programmed message. It might not be calling same function. I’ll figure it out tonight. 

Tom

Principal Solutions Architect
Better Software Solutions, Inc. 
727-437-2771

**Comment by ny4i** [comment]
The code in RITClear received an Abstract run time exception. The code was calling the TNetRadio object incorrectly (earlier implementation model).

**Comment by ny4i** [comment]
Reopening as the send CW is very choppy when sending to the network
