### ISSUE TITLE
New Canadian sections  need to be added

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#632]
I see on this page that NS and NB are now their own sections. I guess that happened on 1/1/2023?

I ask as when I log a contact in TR4W with NS or NB, it puts the section as MAR.

**Comment by n4af** [comment]
Add to that TERRITORIES (TER).
I am so glad  the crazies have added that.
So many contest stations in TER, PE,  and DC that it boggles the mind.

**Comment by n4af** [comment]
Crazies vy qrl
also add Ontario Greater Horseshoe (GH)
This will pick up in 4.119.2

**Comment by n4af** [comment]
tr4w.net has been updated to point to 4.119.4

**Comment by ny4i** [comment]
This now works for NS as well.
