### ISSUE TITLE
Problem with received QTCs in CW-WAE (EU side) when sending QTCs from DX-Stn without a break

### ISSUE THREAD

**Issue by df5en** [n4af/TR4W#651]
Following situation:

- CW WAE contest (EU sight)
- User in Europe asks DX station "QTC?"
- DX station confirms and sends "QTC xx/10" (i.e. 10 QTCs)
- DX station (a bit unfriendly) now sends 10 QTCs without any break
- The problem of the EU station is: It MUST confirm with a <CR> (R, Roger) after each QTC. The beginning of the following QTC is missed.
- The main problem seems to be that a new QTC line is not editable.

Suggested solution:

It should be possible, for example, to go from line 1 of the received QTC with a cursor key to line 2, without sending an "R/Roger". Basically it should be the same function like pressing <CR>, only that no "R" is sent.

**Comment by n4af** [comment]
It seems to me this breaks the idea of QTC's.
*IMO, the originator sends a message (ONE QTC) and then the receiver MUST
QSL*.

*-- Credit for the qtc should NOT occur unless an acknowledgement is  sent
AND received for EACH QTC...*
