### ISSUE TITLE
Need better error handling when cannot connect to cluster

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#67]
If we cannot connect to the cluster for some reason, the error messages are not very good. Sometimes we get a Windows WinSock error or just Command Completed Successfully. This should be beef'ed up and return better, more descriptive errors. It might not hurt to check the server or IP via a ping to test connectivity to the cluster

**Comment by ny4i** [comment]
Oh no :)

You need to back that out :)

I update it so it’s in the repo not because it’s ready. That would make sone people mad if that got out yet. 

Thanks

Tom

Principal Solutions Architect
Better Software Solutions, Inc. 
727-437-2771

**Comment by n4af** [comment]
Ok. I reverted issue 412.

73, Howie
