### ISSUE TITLE
YO DX header rejected

### ISSUE THREAD

**Issue by n4af** [n4af/TR4W#687]
YO DX robot requires
Log file header contest 
YO-DX-HF

**Comment by n4af** [comment]
fix 4.125.5

**Comment by ny4i** [comment]
FYI if it’s just a matter of the Cabrillo name, you can just change that in the contest array. The name in the list of contests doesn’t have to match the Cabrillo or ADIF name. TomPrincipal Solutions ArchitectBetter Software Solutions, Inc. 727-437-2771On Aug 27, 2023, at 9:49 AM, Howie Hoyt ***@***.***> wrote:﻿
Closed #687 as completed.

**Comment by n4af** [comment]
Thanks- good to know.
73, Howie
