### ISSUE TITLE
DARC-WAE-SSB Received QTCs with additional phantom QTCs (EU side)

### ISSUE THREAD

**Issue by df5en** [n4af/TR4W#690]
v.4.126.0

After successfully receiving n QTCs, sometimes there are additional n+1, n+2, [...] QTCs in the log file that have no callsign, all times are 0000 and the serial number is 0.

In Cabrillo it looks like this:

QTC: 21000 PH 2023-09-09 1045 DF5EN 64/10 V3O 0844 CALL01 10
QTC: 21000 PH 2023-09-09 1045 DF5EN 64/10 V3O 0845 CALL02 42
QTC: 21000 PH 2023-09-09 1045 DF5EN 64/10 V3O 0848 CALL03 5
QTC: 21000 PH 2023-09-09 1045 DF5EN 64/10 V3O 0849 CALL04 41
QTC: 21000 PH 2023-09-09 1045 DF5EN 64/10 V3O 0850 CALL05 1
QTC: 21000 PH 2023-09-09 1045 DF5EN 64/10 V3O 0851 CALL06 6
QTC: 21000 PH 2023-09-09 1045 DF5EN 64/10 V3O 0851 CALL07 1
QTC: 21000 PH 2023-09-09 1045 DF5EN 64/10 V3O 0852 CALL08 1
QTC: 21000 PH 2023-09-09 1045 DF5EN 64/10 V3O 0800 CALL09 3
QTC: 21000 PH 2023-09-09 1045 DF5EN 64/10 V3O 0853 CALL10 8
**QTC: 21000 PH 2023-09-09 1045 DF5EN 64/10 V3O 0000 0**

Here is another example where two phantom QTCs appear.

QTC: 28000 PH 2023-09-10 1028 DF5EN 198/4 4X7R 0847 CALL01 80
QTC: 28000 PH 2023-09-10 1028 DF5EN 198/4 4X7R 0851 CALL02 45
QTC: 28000 PH 2023-09-10 1028 DF5EN 198/4 4X7R 0851 CALL03 13
QTC: 28000 PH 2023-09-10 1028 DF5EN 198/4 4X7R 0853 CALL04 1
**QTC: 28000 PH 2023-09-10 1028 DF5EN 198/4 4X7R 0000 0
QTC: 28000 PH 2023-09-10 1028 DF5EN 198/4 4X7R 0000 0**

I am sure that these phantom QTCs were created by the edit function. In the first example I edited ONCE and in the second example I edited TWICE. That was in the contest. I verified it using a dry run after the contest.

Procedure to repeat:
1 Enter/edit QTCs.
2 After the last QTC press: RETURN
3 Pop-Up Windows asks: "Edit QTC....?" Press: YES
4 When you leave the edit function, Pop-Up ask you "Save....?" Press: YES
5. Pop-Up asks you "Edit again or log?" Now press: NO

After step 5, a phantom QTC was generated. This can be repeated n times and creates n phantom QTCs.

Workaround for contesters: Edit the Cabrillo file and delete all phantom QTC lines.

**Comment by n4af** [comment]
Hello Dieter -
Please try 4.126.3 . <https://tr4w.net/4.126/tr4w_setup_4_126.3.exe>

Tks, Howie

**Comment by df5en** [comment]
Great, looks very good. SSB and CW contest, both are OK with v4.126.3. It is no longer possible to generate Phantom QTCs.

Thanks, Howie.

Dieter
