### ISSUE TITLE
Entering 198 in the call window is changing to 40m (7.198) but was on 20

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#704]
expected the radio to tune to 14198 since it was not enough to set the MHz. For some reason, the radio switched to 7.198 from 20m. K4 networking in case that matters.

**Comment by n4af** [comment]
Another problem with adding 60M band.
Fix 4.127.5

**Comment by n4af** [comment]
https://tr4w.net/4.127/tr4w_setup_4_127.5.exe

**Comment by ny4i** [comment]
I’ll test it out. Thanks for fixing. BTW, I enter those as I run into them to address them later after contest. I’m not kicking it over the wall. :) But it doesn’t matter who fixes it. Just wanted to clarify. TomPrincipal Solutions ArchitectBetter Software Solutions, Inc. 727-437-2771813-205-6388 (mobile/text)On Oct 28, 2023, at 9:33 AM, Howie Hoyt ***@***.***> wrote:﻿
https://tr4w.net/4.127/tr4w_setup_4_127.5.exe

**Comment by ny4i** [comment]
Confirmed working. Good fix. Thanks!
