### ISSUE TITLE
Seems to be an issue with the IN7QPNE DOM file

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#763]
I just noticed that the  DOM file in the build has the NE countries inverted. Instead of VTWNH, the DOM has WHNVT. That is incorrect. I will check to see what the DOM checked into GitHub has.

**Comment by ny4i** [comment]
IN7QPNE.dom has not been updated in 3 years so we may have missed an update. I thought I saw some traffic on the reflector about this not long ago. I will check there if someone has a new file.

**Comment by ny4i** [comment]
It looks like the latest file did not make it into MASTER on GitHub. It looks OK in the release. I was running it from Delphi.

I still after all these years am not quite sure how we can end up with a file in the build that is not committed into MASTER. Do you know how that happens in the case of a DOM file. After a build, I would expect everything in the build to be the same as what is downloaded from MASTER.

Tom

**Comment by n4af** [comment]
the github of in7qpne_cty indicates the update was dropped. i will put out
a new refresh.

tks, Howie

**Comment by n4af** [comment]
SIGH. Life is tough.

the file I was sent is not a lot better than the old version.

neqp county abbreviations https://neqp.org/neqp-county-abbreviations/  is
not ascii friendly to developers (as usual) -
so I will need to take some time to callup
a script that converts the insanity to 'county-abbrtev  (space) county
name'  in two columns.

**Comment by ny4i** [comment]
The counties are correct in the latest download so it looks like the right DOM made it into the release. I tested and the NE counties have the state first. They are in lower case for some reason but they are still processed properly.

Closing.
