### ISSUE TITLE
In 3.139.1, when I enter a frequency on call window to change frequency, the call window does not clear

### ISSUE THREAD

**Issue by ny4i** [n4af/TR4W#794]
The rig changes to the desired frequency but the call window is not cleared. This is in CQ mode. Same thing happens in S&P. I just used this in 4.139.0 this past weekend and it worked OK.

**Comment by n4af** [comment]
good testing !
i will take a look later this morning.

**Comment by n4af** [comment]
fixed 4.139.2

**Comment by n4af** [comment]
FB, tks for testing...
