### ISSUE TITLE
Domestic mult needs not displaying on main window, other mult types display OK

### ISSUE THREAD

**Issue by gm0gav** [n4af/TR4W#81]
Domestic mult needs not displaying on main window, other mult types display OK. Effects IOTA, UBA, YODX and all other contests using domestic multipliers

**Comment by n4af** [comment]
Thanks !

73, Howie

http://n4af.net

**Comment by gm0gav** [comment]
On inspection Domestic mult display code had only been partly ported from TRlog, with incomplete sections commented out. Code uncommented and completed, tested with IOTA UBA and YODX contest.

**Comment by n4af** [comment]
Thanks. Just uploaded it to master.

73, howie

http://n4af.net

**Comment by n4af** [comment]
![image](https://cloud.githubusercontent.com/assets/6992208/12791841/e682ff96-ca76-11e5-87c6-bf3c1894002b.png)
