### ISSUE TITLE
4.45.1 Working somone with Alt-D on inactive radio, bandmap spot picks main radio band

### ISSUE THREAD

**Issue by gm0gav** [n4af/TR4W#89]
4.45.1 Working somone with Alt-D on inactive radio, bandmap spot picks main radio band. The resultant spot shows correct frequency but had been given wrong band. So dupes showing on the bandmap as non worked, can show two spots for one call one as a dupe and the other not

**Comment by n4af** [comment]
So far, I have not been able to recreate it.
But think I will open an issue on something that has been bugging me:

I CQ and then the call window is loaded with a blown call spotted of my own
call.
I think load of spots to active radio should be suppressed in in CQmode ?

73, Howie


http://n4af.net

**Comment by n4af** [comment]
not able to reproduce
